# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: youth_read

on:
  workflow_dispatch:
  schedule:
     - cron: '6 1-12/2 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ: ${{ secrets.YOUTH_READ }}
      Y01: ${{ secrets.Y01 }}
      YOUTH: ${{ secrets.YOUTH }}
      YOUTH_READ_1: ${{ secrets.YOUTH_READ_1 }}
      YOUTH_READ_2: ${{ secrets.YOUTH_READ_2 }}
      YOUTH_READ_3: ${{ secrets.YOUTH_READ_3 }}  
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点自动阅读一】'
        if: env.YOUTH_READ
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ }}

      - name: '运行 【中青看点自动阅读二】'
        if: env.Y01
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.Y01 }}
          
      - name: '运行 【中青看点自动阅读三】'
        if: env.YOUTH
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH }}
          
      - name: '运行 【中青看点自动阅读四】'
        if: env.YOUTH_READ_1
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_1 }}
          
      - name: '运行 【中青看点自动阅读五】'
        if: env.YOUTH_READ_2
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_2 }}
             
      - name: '运行 【中青看点自动阅读六】'
        if: env.YOUTH_READ_3
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ_3 }}
